name: dart_gql
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  graphql: ^5.2.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.2
  build_web_compilers: ^4.0.4
