name: dart_gql
description: A Dart/Flutter plugin for GraphQL operations.
version: 0.1.2
maintainers:
  - Pablo Munoz <pjmd89@gmail.com>
homepage: https://github.com/pjmd89/dart_gql

environment:
  sdk: ^3.7.2

dependencies:
  http: ^1.2.1
  graphql: ^5.2.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.2
  build_web_compilers: ^4.0.4
